  {{ PROJECT_NAME }}_db:
    restart: "no"
    image: postgres
    container_name: {{ PROJECT_NAME }}_db
    environment:
      - POSTGRES_PASSWORD={{DATABASE_PASSWORD}}
      - POSTGRES_USER={{DATABASE_USER}}
      - POSTGRES_DB={{DATABASE_NAME}}
    volumes:
      - ../../lu-data/postgres-data:/var/lib/postgresql/data
