  {{ PROJECT_NAME }}_frontend_dev:
    restart: "no"
    container_name: {{ PROJECT_NAME }}_frontend-dev
    image: node:16.14.0
    command: bash -c "cd /app/web && npm install && npm run start-dev"
    volumes:
      - ../../web:/app/web
    environment:
      - EXTERNAL_HOST={{ EXTERNAL_HOST }}
      - EXTERNAL_PROTOCOL={{ EXTERNAL_PROTOCOL }}
    ports:
      - "3000:3000"
      - "8080:8080"
